"""
Repl.py

Class definition for the Repl object.
"""


class Repl:
    """
    The Repl handles IO operations for the backend by accepting UXActions
    generated by the SessionController. The Repl passes information to the
    SessionController as strings representing user input. The Repl is also
    responsible for passing an iterator to the ReadController when the user
    reads results of a query.
    """

    def __init__(self):
        self.__session_controller = None
        self.__post_reader = None

    def set_session_controller(self, session_controller):
        self.__session_controller = session_controller

    def set_post_reader(self, post_reader):
        self.__post_reader = post_reader
