class IParser:
    """ 
    Interface for the parser type

    The Parser has two jobs:
    * Combine grammars and load the resulting combined grammar, replacing the previous one
    * Parse text using the currently loaded grammar, returning a Lark AST

    It is recommended that IParser implementations use the Python Lark parser, as the interface specifies
    that the returned AST match the AST structure generated by the Lark parser
    """

    def set_grammar(self, *grammars):
        """
        Gives the parser multiple grammars to combine into a new
        grammar, which will be loaded as the active grammar for parsing

        Raises GrammarMergeException
        """
        pass

    def parse(self, text):
        """
        Parses a line of text using the grammar created in the most recent call to setSyntax,
        returns the AST produced by the Lark Parser

        raises TextParseException
        """
        pass
